version: "3.8"

services:
    postgres:
        image: postgres:16.4
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - ./supabase/migrations:/docker-entrypoint-initdb.d
